In [3]:
from sklearn.impute import SimpleImputer
import numpy as np

Using imputer like mean, median, mode, constat

In [5]:
data=np.array([
    [1,23,np.nan],
    [12,np.nan,5],
    [np.nan,20,7]  
])

In [ ]:
mean_imputer=SimpleImputer(strategy="mean")
mean_imputed_data=mean_imputer.fit_transform(data)
print(data)
print(mean_imputed_data)

[[ 1. 23. nan]
 [12. nan  5.]
 [nan 20.  7.]]
[[ 1.  23.   6. ]
 [12.  21.5  5. ]
 [ 6.5 20.   7. ]]


In [7]:
median_imputer=SimpleImputer(strategy="median")
median_imputed_data=median_imputer.fit_transform(data)
print(data)
print(median_imputed_data)

[[ 1. 23. nan]
 [12. nan  5.]
 [nan 20.  7.]]
[[ 1.  23.   6. ]
 [12.  21.5  5. ]
 [ 6.5 20.   7. ]]


In [10]:
most_frequent_imputer=SimpleImputer(strategy="most_frequent")
most_frequent_data=most_frequent_imputer.fit_transform(data)
print(data)
print(most_frequent_data)

[[ 1. 23. nan]
 [12. nan  5.]
 [nan 20.  7.]]
[[ 1. 23.  5.]
 [12. 20.  5.]
 [ 1. 20.  7.]]


KNN

In [11]:
from sklearn.impute import KNNImputer


In [12]:
KNN_imputer=KNNImputer(n_neighbors=2)
KNN_imputed_data=KNN_imputer.fit_transform(data)
print(data)
print(KNN_imputed_data)

[[ 1. 23. nan]
 [12. nan  5.]
 [nan 20.  7.]]
[[ 1.  23.   6. ]
 [12.  21.5  5. ]
 [ 6.5 20.   7. ]]
